### ISSUE TITLE
Agilent Chemstation 8453

### ISSUE THREAD

**Issue by Whility** [dd-hebert/agilent-uvvis-to-csv#1]
Hello! Looking for tips on how to open Agilent files i came across your script that allows convert SD files to CSV. However, when I try to use it on my existing files (Agilent 8453), I get an attribute error. I've only recently started learning python, so I didn't delve into your code, but would like to ask for help. An example of few of these files is attached.
![image](https://github.com/dd-hebert/agilent-uvvis-to-csv/assets/75808170/3b88bafa-886e-40df-a349-03e910df214d)
[SSP.zip](https://github.com/dd-hebert/agilent-uvvis-to-csv/files/12261605/SSP.zip)

**Comment by dd-hebert** [comment]
Hi Whility! Thanks for taking interest in my script. I'm looking into this issue now and hope to have it solved for your ASAP.

-DDH

**Comment by dd-hebert** [comment]
Hi Whility, I've identified the issue. It seems that your files are encoded slightly differently than mine and so the script is not correctly finding the absorbance data.

I will work on implementing a fix for this, but in the meantime if you want to get this script up and running for yourself, you just need to change 2 lines of code:
- **Line 84:** Change ``absorbance_data_string = b'\x28\x00\x41\x00\x55\x00\x29\x00'`` to ``absorbance_data_string = b'\x28\x41\x55\x29\x00'``
- **Line 98:** Change ``data_start = spectrum_locations[-1] + 17`` to ``data_start = spectrum_locations[-1] + 1``

Explanation: In my files, there is a header before the absorbance data like "A B S O R B A N C E ( A U ) " with spaces between each character. In your .SD files, it appears as "Absorbance (AU)". The script was thrown off by the missing spaces. Next, the space between the header and the actual data in smaller in your files. In my files, there are 17 spaces, but in your files the data starts immediately after the header.

If you make those two minor changes to the ``uv2csv.py`` file, it should work for you.

Let me know how it goes!

**Comment by dd-hebert** [comment]
And just in case you're not comfortable making those changes yourself, I have a version of the script here with the changes made.
[uv2csv - Whility.zip](https://github.com/dd-hebert/agilent-uvvis-to-csv/files/12262620/uv2csv.-.Whility.zip)

**Comment by dd-hebert** [comment]
Hi Whility, Good news. I have the issue figured out (it's due to slightly different formatting of your files than mine). I'll send the fix over shortly.

**Comment by dd-hebert** [comment]
Hi Whility, 

It will take me a couple days to implement a fix for this, but in the meantime if you want to get this script up and running for yourself, you only need to change 2 lines of code:
- **Line 84:** Change ``absorbance_data_string = b'\x28\x00\x41\x00\x55\x00\x29\x00'`` to ``absorbance_data_string = b'\x28\x41\x55\x29\x00'``
- **Line 98:** Change ``data_start = spectrum_locations[-1] + 17`` to ``data_start = spectrum_locations[-1] + 5``

Explanation: In my files, there is a header before the absorbance data like "A B S O R B A N C E ( A U ) " with spaces between each character. In your .SD files, it appears as "Absorbance (AU)". The script was thrown off by the missing spaces. Next, the space between the header and the actual data is smaller in your files. In my files, there are 17 spaces, but in your files there are 5.

If you make those two minor changes to the ``uv2csv.py`` file, it should work for you.

Let me know how it goes!

**Comment by dd-hebert** [comment]
In case you're uncomfortable making those changes to the code yourself, I have a version of the script with the necessary changes here:
[uv2csv - Whility.zip](https://github.com/dd-hebert/agilent-uvvis-to-csv/files/12262703/uv2csv.-.Whility.zip)

**Comment by Whility** [comment]
Thank you very much for your help! However, of all the spectra in the file, the script only converts the first one. I'm not sure if it was originally intended as such or if I'm having some problems again.

**Comment by dd-hebert** [comment]
Hi Whility,

It seems the problem come from slightly different handling of the data files between different versions of the Agilent software. On my system, an .SD file will only ever contain a **single** spectrum. When collecting multiple spectra into a single file, we use _kinetics mode_ and collect them into a .KD file.

Until I get the chance to take a closer look at the structure of your files, I had an idea that might be worth trying. If you make a copy of your .SD file and rename it with .KD file extension, the script might be able to export all the spectra instead of just the first one.

I will look into more closely this weekend.

Cheers,
DDH

**Comment by dd-hebert** [comment]
Hey @Whility 
I tested changing the file extension from .SD to .KD and it works!! That might be a worthy temporary solution for you until I can adjust the script to be more flexible with handling different versions of the Agilent software (hopefully sometime this weekend). Before I close this issue, could you provide any additional information about the model of spectrometer and version of Chemstation you're using?

**Comment by Whility** [comment]
Thanks again! Everything works great. I'm pretty sure it's an Agilent 8453 spectrophotometer. I'll be able to check the details and Chemstation version after the weekend.

**Comment by dd-hebert** [comment]
Great! If you could provide the revision number of your version of Chemstation, that would be very helpful!
![Chemstation_revision_number](https://github.com/dd-hebert/agilent-uvvis-to-csv/assets/39543390/f17bde71-044a-4ebe-8288-98f30a8e99db)

**Comment by Whility** [comment]
I finally managed to check the version of the program installed to the spectrophotometer. It's 845x UV-Visible System; UV-Visible ChemStation Rev. A.08.03 [71]

**Comment by dd-hebert** [comment]
Thanks, Whility!

I've updated the script and the new version should work directly with your .SD files now without any modifications. Thanks for opening this issue and helping me improve the code!

Cheers,
-DDH
