### ISSUE TITLE
Sample Names

### ISSUE THREAD

**Issue by Whility** [dd-hebert/agilent-uvvis-to-csv#2]
Hello again! This time I came not with a bug, but with a proposal. Is it possible to decode from SD files not only the absorption spectrum itself, but also the names of the samples? When reading SD files, I can find the approximate location of the sample names, but I have trouble decoding them. This would be quite useful, especially if you need to open some old files when no one remembers what specific position the required spectra were in

**Comment by dd-hebert** [comment]
Hi Whility!

Thanks for the suggestion. I'm open to adding this feature to the script. I took a look at some of the .SD files you sent me previously and found some sample names, however I'm having a bit of trouble decoding them as well.

Here's an example of some sample names I found in **220719-1.SD**:

![sample_names_whility](https://github.com/dd-hebert/agilent-uvvis-to-csv/assets/39543390/58fe47b4-92bf-41a7-81b7-c98a0373a144)

Do you have any ideas what these sample names are supposed to be? Are they words or numbers? Is it possible that you can send me a .SD file with known sample names? I might be able to reverse engineer the encoding that way.

Best,
-DH

**Comment by Whility** [comment]
Thanks for the answer! Typically, sample names include both numbers and words. I will try to prepare spectra with the known names in the coming days. For now I can say that the name of the first recorded spectrum in the previously sent files is most likely “water”.

**Comment by dd-hebert** [comment]
Thanks Whility!

Actually, there is no need to prepare a new .SD file with known sample names. I opened the .SD file in ChemStation and found the sample names for **220719-1.SD**.

 I'll work on trying to decode the sample names from inside the .SD files.

-DH

**Comment by dd-hebert** [comment]
Good news! I figured it out! I'll work on implementing the sample names into the script. I should have the changes made to the script in the coming days.

**Comment by dd-hebert** [comment]
Hi Whility,

I've added support for sample names to the script. Now when you parse and export .csv from a .SD file, they will be named as:
`{spectrum number} - {sample name}.csv`.

If no sample name is given, then the exported file will just have the name `{spectrum number}.csv`.

Sample names are currently only supported for .SD files. I may add support for sample names with .KD files in the future if it is needed.

Let me know if you encounter any issues with the new version!

Best,
-DH
