### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by pandamal0** [dd-hebert/agilent-uvvis-to-csv#3]
Hi i'm not much of a programmer but i've been using this to plot some spectra, usually go well but for these specific samples this error has ocurred, what can i do to correct it?

**Comment by dd-hebert** [comment]
Hi @pandamal0, it looks like the error is due to your file containing an unrecognized character. Can you give me a bit more information so I can try and fix it?

- What kind of file are you trying to convert? .SD or .KD?
- If you're trying to convert a .SD file, do the spectra have sample names?
- What version of Chemstation was used to create the file?

If it's possible, can you share the problematic file here? I can solve the issue much faster that way.

Best,
-DH

**Comment by pandamal0** [comment]
so i was using an sd file with names, but in my case I retrive the archives directly from the uv-vis (model HP 8453) that has an proper file manager, but after some time i tried to change the range, and it worked but seens a bit strange (because i could not pick anything after 900nm) and once the others archives from the same spectrofotometer worked fine without setting nothing.

I can work with those ones i think, because i work close to 200 nm but in 1000 actually there is a peak that shoud'nt be there

**Comment by dd-hebert** [comment]
I think the script might have issues with some non-English characters/symbols in the sample names. Another possibility is you're using a different version of Agilent UV-Vis Chemstation which encodes the files slightly differently.

Are you able to share the .SD file?

**Comment by pandamal0** [comment]
sure, I will send you one that worked (chlorophyll) and one of the ones that the error occurred (caffeine)

[teste.zip](https://github.com/dd-hebert/agilent-uvvis-to-csv/files/13687315/teste.zip)

**Comment by dd-hebert** [comment]
Thanks for this. I'll take a look a hopefully release a fix sometime this weekend.

-DH

**Comment by dd-hebert** [comment]
Hi @pandamal0, I've just released an update for the script. It should properly parse the sample names from your .SD files now.

If you have any other issues or ideas for suggestions, let me know so I can improve this script!

Best,
-DH

**Comment by dd-hebert** [comment]
Hi @pandamal0, I've just released an update for the script. It should properly parse the sample names from your .SD files now.

If you have any other issues or ideas for suggestions, let me know so I can improve this script!

Best,
-DH
